# Canonical preset schema mapping Python normalized fields to C++ DSP inputs
version: 1
units:
  time: seconds
  frequency: Hz
  level: linear_or_db

fields:
  envelope:
    attack: { type: number, min: 0.0, max: 10.0, unit: seconds }
    decay:  { type: number, min: 0.0, max: 10.0, unit: seconds }
    sustain:{ type: number, min: 0.0, max: 1.0 }
    release:{ type: number, min: 0.0, max: 20.0, unit: seconds }
  filter:
    cutoff:    { type: number, min: 20.0, max: 20000.0, unit: Hz }
    resonance: { type: number, min: 0.0, max: 0.99 }
    envelope_amount: { type: number, min: 0.0, max: 1.0 }
  oscillator:
    detune: { type: number, min: 0.5, max: 2.0, note: ratio of base freq }
    mix_ratios: { type: array, items: number, note: sum to 1.0 }
  fx:
    - type: { type: string }
      mix:  { type: number, min: 0.0, max: 1.0 }

contract:
  request:
    prompt: { type: string }
    role:   { type: string, enum: [PAD, BASS, LEAD, DRUM, PERCUSSION, AMBIENT, TEXTURE, UNKNOWN] }
    context:
      tempo: { type: number, min: 20.0, max: 300.0 }
      key:   { type: integer, min: 0, max: 11 }
      scale: { type: string }
    constraints:
      maxCPU: { type: number, min: 0.0, max: 1.0 }
      maxLatency: { type: number, min: 1.0, max: 100.0, unit: ms }
      lufsTarget: { type: number, min: -36.0, max: 0.0, unit: LUFS }
      truePeakLimit: { type: number, min: -12.0, max: 0.0, unit: dBTP }
